version: '3'
services:
  #
  # Servers
  #
 
  geth01:
    build: ./images/ethereum
    networks:
      ethereum:
        ipv4_address: ${NODE01_IP:?}
    ports:
      - "8545:8545"
    volumes:
      - ./:/root
    environment:
      GENESIS_FILE: ./files/shared/genesis.json
      DATA_DIR: .tmp/node01
    working_dir: /root
    command: [
      "--networkid", "${NETWORK_ID:?}",
      "--authrpc.port", "8551",

      "--http",
      "--http.api", "eth,personal",
      "--http.addr", "0.0.0.0",
      "--allow-insecure-unlock",

      "--nodekey", "./files/node01/nodekey",
      "--keystore", "./files/node01/keystore",
      # Miner unlocking
      "--unlock", "0x6ce0ba981dd9b3bc259bbd868be14f957dbe6dcf",
      "--password", "./files/node01/password_6ce0ba981dd9b3bc259bbd868be14f957dbe6dcf.txt",
      # Mining (PoA)
      "--mine",
      "--miner.etherbase", "0x6ce0ba981dd9b3bc259bbd868be14f957dbe6dcf",
      # Bootstrap Node Settings
      "--port", "${NODE01_PORT:?}",
      "-nat", "extip:${NODE01_IP:?}",
    ]

  geth02:
    build: ./images/ethereum
    networks:
      ethereum:
    volumes:
      - ./:/root
    environment:
      GENESIS_FILE: ./files/shared/genesis.json
      DATA_DIR: .tmp/node02
    working_dir: /root
    command: [
      "--networkid", "${NETWORK_ID:?}",
      "--authrpc.port", "8551",

      "--datadir", ".tmp/node02",
      "--nodekey", "./files/node02/nodekey",
      "--keystore", "./files/node02/keystore",
      # Member Node Settings
      "--bootnodes", "${NODE01_ID:?}",
    ]

  #
  # Commands
  #

  create-genesis-json:
    profiles: [command]
    image: golang:1.20.1
    volumes:
      - ./app/:/app/
    entrypoint: go run /app/create-genesis-json/main.go

  geth:
    profiles: [command]
    build: images/ethereum
    networks:
      ethereum:
    volumes:
      - ./:/root
      - ./.tmp/node02/.geth/:/data/node02
    working_dir: /root
    entrypoint: geth
    command: attach .tmp/node01/geth.ipc

  deploy-contract:
    profiles: [command]
    build: ./images/deploy-contract
    networks:
      ethereum:
    volumes:
      - ./app/request/:/work
      - ./solidity/:/solidity
      - ./files/node01/:/input/password
      - .tmp/file:/output/file
    environment:
      ETH_URL: "http://${NODE01_IP:?}:8545"
    working_dir: /work
    command: [
      "--account", "6ce0ba981dd9b3bc259bbd868be14f957dbe6dcf",
      "--password", "/input/password/password_6ce0ba981dd9b3bc259bbd868be14f957dbe6dcf.txt",
      "--abi", "/solidity/output/SingleNumRegister.abi",
      "--bin", "/solidity/output/SingleNumRegister.bin",
      "--out", "/output/file/outfile.txt"
    ]
 
networks:
  ethereum:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
